<?php
/**
 *
 * OpenRAUserAccounts. An extension for the phpBB Forum Software package.
 *
 * @copyright (c) 2018, The OpenRAUserAccounts authors
 * @license GNU General Public License, version 2 (GPL-2.0)
 *
 */

if (!defined('IN_PHPBB'))
{
	exit;
}

if (empty($lang) || !is_array($lang))
{
	$lang = array();
}

$lang = array_merge($lang, array(
	'UCP_ACCOUNTS'									=> 'OpenRA account',
	'UCP_ACCOUNTS_ADD_KEY'							=> 'Add authentication key',
	'UCP_ACCOUNTS_ADD_KEY_EXPLAIN'					=> 'Connect your forum account to as many OpenRA installations as you want and authenticate yourself to other players ingame.',
	'UCP_ACCOUNTS_MANAGE_KEYS'						=> 'Manage keys',
	'UCP_ACCOUNTS_MANAGE_KEYS_EXPLAIN'				=> 'The list shows your active authenticatin keys. Revoked authentication keys are not shown.',
	'UCP_ACCOUNTS_SELECT_BADGES'					=> 'Select badges',
	'UCP_ACCOUNTS_SELECT_BADGES_EXPLAIN'			=> 'Here you find the badges that are available for your account.',
	'UCP_ACCOUNTS_ORDER_BADGES'						=> 'Order badges',
	'UCP_ACCOUNTS_ORDER_BADGES_EXPLAIN'				=> 'The badges here will be shown in your profile information. You can change the order or add more badges from the \'Select badges\' page.',
	'INPUT_KEY'										=> 'Enter authentication key',
	'INPUT_KEY_EXPLAIN'								=> 'Paste the authentication key generated by your OpenRA install.',
	'KEY_SAVED'										=> 'Authentication key has been saved.',
	'INVALID_KEY'									=> 'Invalid authentication key.',
	'DUPLICATE_KEY'									=> 'This authentication key is already in use.',
    'DUPLICATE_KEY_REVOKED'							=> 'This authentication key is already used and revoked.',
    'CAN_NOT_ADD_KEY'                               => 'Unable to add authentication key. Please try again or submit an issue to the <a href="https://github.com/OpenRA/openrauseraccounts"> OpenRAUseraccounts repository</a> if the problem persists.',
	'NO_KEYS'										=> 'No authentication keys.',
	'KEY_NOT_ACCESSED'								=> 'Authentication key not accessed.',
	'TOTAL_KEYS'									=> array(1 => '%d key', 2 => '%d keys'),
	'FINGERPRINT'									=> 'Fingerprint',
	'REGISTERED'									=> 'Registered',
	'LAST_ACCESS'									=> 'Last accessed',
	'REVOKE_ALL'									=> 'Revoke all keys',
    'REVOKE_MARKED'								    => 'Revoke marked keys',
	'ALL_KEYS_REVOKED'                              => 'All authentication keys have been revoked.',
	'SELECTED_KEYS_REVOKED'							=> 'The selected authentication keys have been revoked .',
	'CAN_NOT_REVOKE_KEY'							=> 'Unable to revoke authentication key. Please try again or submit an issue to the <a href="https://github.com/OpenRA/openrauseraccounts"> OpenRAUseraccounts repository</a> if the problem persists.',
	'BADGE_LABEL'									=> 'Badge label',
	'BADGE_ICON'									=> 'Badge icon',
	'NO_PROFILE_BADGES'								=> 'No profile badges',
	'NO_BADGES_AVAILABLE'							=> 'No badges available.',
	'BADGES_NOT_DISPLAYED'							=> 'Badges below will not be shown in your profile information.',
	'SELECTION'										=> 'SELECTION',
	'ORDER_BADGES_TABLE_DESC'						=> 'Use the arrows to manage the order of your profile badges.',
	'SELECT_BADGES_TABLE_DESC'						=> 'Select badges to show them in your profile information.',
	'AGREEMENT'										=> 'I agree to OpenRA\'s <a href="https://forum.openra.net/privacypolicy/policy">privacy policy</a> and acknowledge that my OpenRA profile may be disabled without warning if I am found to have exploited or abused the system to the detriment of other players.',
	'SELECTED_BADGES_SAVED'							=> 'Your badge selection has been updated. Visit the \'Order badges\' page to view and change the order of your profile badges.',
	'SELECTION_NOT_UPDATED'							=> 'Your selection is already up to date.',
    'ALL_USER_BADGES_REMOVED'						=> 'All badges have been successfully removed from your profile.',
	'CAN_NOT_MOVE_UBADGE'							=> 'Unable to change badge order. Please try again or submit an issue to the <a href="https://github.com/OpenRA/openrauseraccounts"> OpenRAUseraccounts repository</a> if the problem persists.',
));
